---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
- name: pal-tracker
- name: version

outputs:
- name: build-output

run:
  path: bash
  args:
    - -exc
    - |
      export DEBIAN_FRONTEND="noninteractive"
      apt-get update
      apt-get -y install mysql-server
      service mysql start

      cd pal-tracker

      mysql -uroot < databases/create_databases.sql

      ./gradlew testMigrate clean build || (service mysql stop && exit 1)

      cp applications/allocations-server/build/libs/allocations-server.jar ../build-output/allocations-server-`cat ../version/number`.jar
      cp applications/backlog-server/build/libs/backlog-server.jar ../build-output/backlog-server-`cat ../version/number`.jar
      cp applications/registration-server/build/libs/registration-server.jar ../build-output/registration-server-`cat ../version/number`.jar
      cp applications/timesheets-server/build/libs/timesheets-server.jar ../build-output/timesheets-server-`cat ../version/number`.jar

      service mysql stop
